name: flake8 check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v4.2.0
        with: 
          python-version: 3.9
      
      # Runs a set of commands using the runners shell
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --select=E --exclude=prompts.py --max-line-length 100 --extend-ignore E241 core/